sonar.projectKey=tinuvi_django-q2-full-of-juice
sonar.organization=tinuvi

sonar.language=py
sonar.python.version=3.12

sonar.sources=django_q
sonar.tests=tests
sonar.exclusions=**/migrations/**,tests/**
sonar.coverage.exclusions=**/migrations/**,tests/**

sonar.python.coverage.reportPaths=tests-reports/coverage.xml
sonar.python.xunit.reportPath=tests-reports/junit.xml

sonar.verbose=false
