import { expect, test } from '@playwright/test';

import { enqueue, waitForTask } from '../helpers/api';

test.describe('basic enqueue', () => {
  test('noop task runs and reports success', async ({ request }) => {
    const enqueued = await enqueue(request, { task: 'noop', args: ['hello'] });

    const finished = await waitForTask(request, enqueued.task_id);
    expect(finished.success).toBe(true);
    expect(finished.func).toBe('tasks_app.tasks.noop');
    // The Task.name (slug-ish) is auto-generated by django-q2; just sanity-check it exists.
    expect(finished.name).toBeTruthy();
    // noop returns {args, kwargs}; we sent one positional arg.
    expect(finished.result).toMatchObject({ args: ['hello'], kwargs: {} });
  });
});
