name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lint-formatter
        run: docker compose -f test-services-docker-compose.yaml run --rm --remove-orphans lint-formatter

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        run: docker compose -f test-services-docker-compose.yaml run --rm --remove-orphans integration-tests
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: tests-reports/
